Repository clearlydefined/curated-data, pull requests merged in 2020-07, with the labels that each got.

#4342 Add Other License
  curations/nuget/nuget/-/Newtonsoft.Json.Schema.yaml
Labels: need clarification from component author

#4175 Declared License
  curations/nuget/nuget/-/Newtonsoft.Json.Schema.yaml
Labels: need clarification from component author

#4628 Add MIT License
  curations/npm/npmjs/-/storybook-chromatic.yaml
Labels: need clarification from component author

#4902 DiffPlex/1.2.1
  curations/nuget/nuget/-/DiffPlex.yaml
Labels: response requested from curator

#4550 gensim 3.8.3
  curations/pypi/pypi/-/gensim.yaml
Labels: response requested from curator

#5067 dom4j/2.1.1
  curations/maven/mavencentral/org.dom4j/dom4j.yaml
Labels: response requested from curator

#5026 Rx-Core/2.2.2
  curations/nuget/nuget/-/Rx-Core.yaml
Labels: response requested from curator

#4958 Microsoft.CodeAnalysis.Workspaces.Common/3.0.0
  curations/nuget/nuget/-/Microsoft.CodeAnalysis.Workspaces.Common.yaml
Labels: response requested from curator

#4963 reactive-streams/1.0.3
  curations/maven/mavencentral/org.reactivestreams/reactive-streams.yaml
Labels: response requested from curator

#4979 Confluent.Kafka 1.3.0
  curations/nuget/nuget/-/Confluent.Kafka.yaml
Labels: response requested from curator

#5185 regex 2020.5.7
  curations/pypi/pypi/-/regex.yaml
Labels: community feedback requested
