Repository clearlydefined/curated-data, pull requests merged in 2021-09, with the labels that each got.

#13367 Update the source information
  curations/npm/npmjs/-/monitor-event-loop-delay.yaml
Labels: researching

#13369 Update the source information
  curations/npm/npmjs/-/minstache.yaml
Labels: researching

#13789 TestStack.BDDfy 4.3.2
  curations/nuget/nuget/-/TestStack.BDDfy.yaml
Labels: feedback requested

#13782 platform 3.4.0
  curations/maven/mavencentral/net.java.dev.jna/platform.yaml
Labels: feedback requested

#13826 yaml/0.2.3
  curations/npm/npmjs/-/yaml.yaml
Labels: merge conflict

#13779 jQuery.vsdoc 1.5.1
  curations/nuget/nuget/-/jQuery.vsdoc.yaml
Labels: feedback requested

#14421 JetBrains.ReSharper.CommandLineTools 2021.2.0
  curations/nuget/nuget/-/JetBrains.ReSharper.CommandLineTools.yaml
Labels: merge conflict
