Repository clearlydefined/curated-data, pull requests merged in 2021-12, with the labels that each got.

#15199 xmldom 0.1.16
  curations/npm/npmjs/-/xmldom.yaml
Labels: feedback requested

#15426 Discovered Licenses contained NOASSERTIONS
  curations/git/github/jetstack/cert-manager.yaml
Labels: issue

#15480 Declared license was "Apache 2.0 AND NOASSERTION" which is incorrect
  curations/git/github/coreos/etcd.yaml
Labels: issue

#15260 org.slf4j/slf4j-nop/1.5.3
  curations/maven/mavencentral/org.slf4j/slf4j-nop.yaml
Labels: feedback requested

#15590 jersey-test-framework-core 1.9
  curations/maven/mavencentral/com.sun.jersey.jersey-test-framework/jersey-test-framework-core.yaml
Labels: merge conflict

#15558 librdkafka.redist 1.4.0
  curations/nuget/nuget/-/librdkafka.redist.yaml
Labels: merge conflict

#15877 EntityFramework.MappingAPI 6.0.0.7
  curations/nuget/nuget/-/EntityFramework.MappingAPI.yaml
Labels: feedback requested

#15775 AutoItX.Dotnet 3.3.14.2
  curations/nuget/nuget/-/AutoItX.Dotnet.yaml
Labels: feedback requested

#15569 SQLinq 3.0.1-b5
  curations/nuget/nuget/-/SQLinq.yaml
Labels: feedback requested

#15540 jaxen 1.1.1
  curations/maven/mavencentral/jaxen/jaxen.yaml
Labels: feedback requested

#15570 SQLinq.Dapper 1.5.1-b5
  curations/nuget/nuget/-/SQLinq.Dapper.yaml
Labels: feedback requested

#15539 jainslee-api 1.1
  curations/maven/mavencentral/javax.slee/jainslee-api.yaml
Labels: feedback requested

#15946 set-filter 25.1.0
  curations/npm/npmjs/@ag-grid-enterprise/set-filter.yaml
Labels: feedback requested

#15963 jbcrypt 0.3m
  curations/maven/mavencentral/org.mindrot/jbcrypt.yaml
Labels: feedback requested

#16504 pcf-scripts 1.3.1
  curations/npm/npmjs/-/pcf-scripts.yaml
Labels: merge conflict
