Repository clearlydefined/curated-data, pull requests merged in 2022-03, with the labels that each got.

#18037 ansi-to-react 4.0.3-alpha.0
  curations/npm/npmjs/-/ansi-to-react.yaml
Labels: merge conflict

#18073 net.java.dev.jna:jna-platform 5.9.0
  curations/maven/mavencentral/net.java.dev.jna/jna-platform.yaml
Labels: feedback requested

#18291 jquery/jquery 4dec426aa2a6cbabb1b064319ba7c272d594a688
  curations/git/github/jquery/jquery.yaml
Labels: issue
